# Generated by Django 4.1 on 2022-08-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Artists",
            new_name="Artist",
        ),
        migrations.RenameModel(
            old_name="Countries",
            new_name="Country",
        ),
    ]
