# Generated by Django 4.1 on 2022-08-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_rename_artists_artist_rename_countries_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="artist",
        ),
        migrations.RemoveField(
            model_name="gender",
            name="artist",
        ),
        migrations.AddField(
            model_name="artist",
            name="country",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artists.country",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="gender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="artists.gender",
            ),
        ),
    ]
