# Generated by Django 4.1 on 2022-08-21 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0004_rename_country_country_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                choices=[
                    ("US", "America"),
                    ("FR", "France"),
                    ("UK", "United Kingdom"),
                    ("ES", "Spain"),
                    ("GE", "Germany"),
                ],
                max_length=16,
            ),
        ),
    ]
