# Generated by Django 4.1 on 2022-08-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0005_alter_country_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artist",
            name="country",
        ),
        migrations.RemoveField(
            model_name="artist",
            name="gender",
        ),
    ]
